%YAML:1.0
---
image_width: 1280
image_height: 720
camera_name: camera

camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [490.980065, 1.448770, 639.427696,
         0.0, 492.132778, 357.232355,
         0.0, 0.0, 1.0]

distortion_model: plumb_bob
distortion_coefficients: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [0.487826, -1.851282, 1.209359, -0.068021, 0.0]

rectification_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]

projection_matrix: !!opencv-matrix
  rows: 3
  cols: 4
  dt: d
  data: [490.980065, 1.448770, 639.427696, 0.0,
         0.0, 492.132778, 357.232355, 0.0,
         0.0, 0.0, 1.0, 0.0]